version: 1
builder:
  configs:
  - platform: macosspm
    target: StatKit
  - platform: ios
    target: StatKit
  - platform: tvos
    target: StatKit
  - platform: watchos
    target: StatKit
  - platform: visionos
    target: StatKit
  - platform: linux
    target: StatKit
  - documentation_targets: [StatKit]
    custom_documentation_parameters: [--include-extended-types]
