opt_in_rules:
  - missing_docs

included:
  - Sources

excluded:
  - .git
  - .github
  - .swiftpm
  - Package.swift
  - Tests

analyzer_rules:
  - unused_declaration
  - unused_import

disabled_rules:
  - trailing_whitespace
  - switch_case_alignment
  - opening_brace
  - identifier_name
  - trailing_comma
  - large_tuple

function_body_length:
  warning: 50
  error: 80
