included:
  - Sources
  - Tests

excluded:
  - .git
  - .github
  - .swiftpm
  - Package.swift

analyzer_rules:
  - unused_declaration
  - unused_import

disabled_rules:
  - trailing_whitespace
  - switch_case_alignment
