version: "3.8"
services:
  linux-tests:
    container_name: linux-tests
    image: swift:5.5
    volumes:
      - ./:/statkit
    working_dir: /statkit
    command: swift test -c release --parallel
  
  linter:
    container_name: linter
    image: norionomura/swiftlint:0.45.0_swift-5.5.1
    volumes:
      - ./:/statkit
    working_dir: /statkit
    command: swiftlint lint --strict
