name: Code Style

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Swiftlint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
