name: Quality Assurance

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      
  SwiftLint:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Swiftlint
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
