name: Test Suite

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, macos-14, macos-15]
        swift: ["6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test -c release --parallel
