name: Test Suite

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.1.app

jobs:
  macOS:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v3
    - name: Run macOS Tests
      run: swift test -c release --parallel
      
  Linux:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'
    - name: Run Linux Tests
      run: swift test -c release --parallel
