name: Test Suite

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  macOS:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run macOS Tests
      run: swift test -c release --parallel
      
  Linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Linux Tests
        run: swift test -c release --parallel
